// Türkiye Yüzyılı Maarif Modeli (TYMM) 2026 — Ortaöğretim (Lise 9, 10, 11, 12. Sınıflar)
// Resmî MEB Ortaöğretim Matematik Dersi Öğretim Programı Kapsamı

import { Level } from '@/types/curriculum';

export const liseLevel: Level = {
  id: 'lise',
  title: 'Lise',
  subtitle: 'Hazırlık, 9, 10, 11 ve 12. Sınıf',
  gradeRange: 'Hazırlık - 12. Sınıf',
  description: 'T.C. Millî Eğitim Bakanlığı Türkiye Yüzyılı Maarif Modeli (TYMM) 2026 Ortaöğretim Matematik Dersi Öğretim Programı.',
  grades: [
    // =========================================================================
    // HAZIRLIK SINIFI (108 Ders Saati — 11 Öğrenme Çıktısı — 5 Tema)
    // =========================================================================
    {
      gradeNumber: 0,
      title: 'Hazırlık Sınıfı',
      subtitle: 'Doğrusal İlişkiler, Mantıksal Çıkarım, Kriptoloji ve Geometrik İnşalar',
      description: 'T.C. Millî Eğitim Bakanlığı Türkiye Yüzyılı Maarif Modeli Hazırlık Sınıfı Matematik Programı: Doğrusal ilişkiler, mantıksal çıkarım stratejileri, sayı örüntüleri ve kriptoloji, pergel-cetvel geometrik inşaları, fraktallar, süsleme-kaplamalar ve istatistiksel eleştirel değerlendirme.',
      themes: [
        // 1. TEMA: NİCELİKLER VE DEĞİŞİMLER (20 Ders Saati - 1 Çıktı)
        {
          id: 'tymm-h-nicelikler',
          code: 'MAT.H.1',
          orderNumber: 1,
          themeName: 'Nicelikler ve Değişimler',
          fullTitle: 'MAT.H.1. Nicelikler ve Değişimler',
          category: 'fonksiyon',
          lessonHours: 20,
          outcomeCount: 1,
          description: 'Doğrusal ilişkiler içeren problemlerin matematiksel araç ve teknolojilerden yararlanılarak modellenmesi ve çözülmesi.',
          colorTheme: '#8b5cf6',
          topics: [
            {
              id: 'h-dogrusal-iliski-modelleri',
              title: 'Doğrusal İlişkiler ve Grafiksel Modeller',
              code: 'MAT.H.1.1',
              category: 'fonksiyon',
              badge: 'Doğrusal İlişkiler',
              description: 'Doğrusal ilişki içeren problemlerin tablo, cebirsel ve grafik temsilleri ile incelenmesi, eğim ve öteleme dinamikleri.',
              learningOutcomes: [
                'Doğrusal ilişkiler içeren problemlerin çözümlerinde matematiksel araç ve teknolojilerden yararlanabilme.',
                'Doğrusal ilişkilerin grafik ve cebirsel temsillerindeki katsayıları (eğim ve y-kesen) yorumlayabilme.',
              ],
              activities: [
                {
                  id: 'act-h-dogrusal-egim',
                  title: '📈 Doğrusal Değişim ve Eğim Simülatörü',
                  category: 'fonksiyon',
                  description: 'y = mx + n doğrusal modelinde eğim (m) ve sabit terimi (n) değiştirerek sıcaklık değişimi ve ücret tarifelerini modelleyin.',
                  learningGoal: 'Doğrusal ilişkilerin eşit aralıklarda eşit farklarla değişim mantığını kavramak.',
                  folderColor: '#8b5cf6',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Doğrunun eğimini ve y-kesenini ayarlayarak hedef grafiği oluşturun.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Doğrusal ilişkiler ve eğim analizi başarıyla tamamlandı.',
                },
                {
                  id: 'act-h-koordinat-model',
                  title: '🎯 Dik Koordinat Sisteminde Problem Modelleme',
                  category: 'cebir',
                  description: 'Gerçek yaşam verilerini dik koordinat sisteminde noktalarla temsil edip doğrusal fonksiyon modeline dönüştürün.',
                  learningGoal: 'Sözel, tablo ve grafik temsilleri arasında dinamik geçiş yapabilmek.',
                  folderColor: '#3b82f6',
                  previewType: 'coordinate_grid',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Koordinat düzleminde verilen noktaları inceleyin ve doğrusal modeli oluşturun.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Koordinat modeli ve doğrusal ilişki başarıyla modellendi.',
                },
              ],
            },
          ],
        },

        // 2. TEMA: MANTIKSAL ÇIKARIM (20 Ders Saati - 1 Çıktı)
        {
          id: 'tymm-h-mantik',
          code: 'MAT.H.2',
          orderNumber: 2,
          themeName: 'Mantıksal Çıkarım',
          fullTitle: 'MAT.H.2. Mantıksal Çıkarım',
          category: 'sayi',
          lessonHours: 20,
          outcomeCount: 1,
          description: 'Mantıksal çıkarım gerektiren problemlerin ağaç şeması, sistematik listeleme, diyagram ve tablo temsilleriyle çözülmesi.',
          colorTheme: '#ec4899',
          topics: [
            {
              id: 'h-mantiksal-cikarim-stratejileri',
              title: 'Mantıksal Çıkarım ve Çözüm Stratejileri',
              code: 'MAT.H.2.1',
              category: 'sayi',
              badge: 'Mantıksal Çıkarım',
              description: 'Zekâ problemleri, eşleştirme bulmacaları, ağaç şeması ve sistematik listeleme yöntemleriyle mantıksal çıkarım yapma.',
              learningOutcomes: [
                'Mantıksal çıkarım gerektiren problemleri farklı stratejiler kullanarak çözebilme.',
                'Ağaç şeması, diyagram ve tablo temsillerini etkin problem çözme aracı olarak kullanabilme.',
              ],
              activities: [
                {
                  id: 'act-h-mantik-agac',
                  title: '🌳 Ağaç Şeması ve Sistematik Listeleme',
                  category: 'sayi',
                  description: 'Tüm olası durumları ağaç şeması ve sistematik listeleme ile görselleştirerek mantıksal çıkarımda bulunun.',
                  learningGoal: 'Sonlu sayıda nicelik içeren mantıksal problemleri uygun temsillerle çözmek.',
                  folderColor: '#ec4899',
                  previewType: 'pattern_blocks',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Olası durumları ağaç şeması üzerinde adım adım analiz edin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Mantıksal çıkarım stratejilerini başarıyla uyguladınız.',
                },
                {
                  id: 'act-h-tablo-cikarim',
                  title: '📋 İkili Eşleştirme ve Mantık Tablosu',
                  category: 'sayi',
                  description: 'Kişiler, branşlar ve puanlar arasındaki ilişkileri mantık tablosu üzerinde inşa edip bilinmeyenleri bulun.',
                  learningGoal: 'Tablo temsili üzerinden mantıksal çıkarım ve tümdengelim yapmak.',
                  folderColor: '#f59e0b',
                  previewType: 'data_barchart',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Mantık tablosundaki ipuçlarını birleştirerek doğru eşleştirmeleri yapın.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Mantık tablosu ile doğru çıkarımlara ulaştınız.',
                },
              ],
            },
          ],
        },

        // 3. TEMA: ALGORİTMA VE BİLİŞİM (26 Ders Saati - 3 Çıktı)
        {
          id: 'tymm-h-algoritma',
          code: 'MAT.H.3',
          orderNumber: 3,
          themeName: 'Algoritma ve Bilişim',
          fullTitle: 'MAT.H.3. Algoritma ve Bilişim',
          category: 'cebir',
          lessonHours: 26,
          outcomeCount: 3,
          description: 'Sonlu sayı örüntülerine yönelik tümevarımsal akıl yürütme, şifreli metinlerin çözümü, Sezar çarkı ve kriptoloji algoritmaları.',
          colorTheme: '#06b6d4',
          topics: [
            {
              id: 'h-oruntu-kriptoloji',
              title: 'Sayı Örüntüleri, Şifreleme ve Kriptoloji',
              code: 'MAT.H.3.1-3',
              category: 'cebir',
              badge: 'Algoritma & Şifreleme',
              description: 'Sayı örüntülerinin genel terimleri, şifreleme kuralları, Sezar çarkı ve modüler şifreleme mantığı.',
              learningOutcomes: [
                'Sonlu sayı örüntülerine yönelik tümevarımsal akıl yürütebilme.',
                'Şifreli metinleri çözebilmek için tümevarımsal akıl yürütebilme.',
                'Şifreli metinler oluşturabilmek için analojik akıl yürütebilme.',
              ],
              activities: [
                {
                  id: 'act-h-sezar-sifre',
                  title: '🔐 Sezar Çarkı ve Kriptoloji Algoritması',
                  category: 'cebir',
                  description: 'Alfabedeki harfleri belirli bir adım öteleyerek şifreli metinler oluşturun ve verilen şifreli mesajları deşifre edin.',
                  learningGoal: 'Algoritmik şifreleme mantığını ve sayı örüntülerini kavramak.',
                  folderColor: '#06b6d4',
                  previewType: 'probability_spinner',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Şifreleme çarkını döndürerek anahtar sayısını belirleyin ve metni şifreleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Kriptoloji ve Sezar şifreleme algoritmasını başarıyla uyguladınız.',
                },
                {
                  id: 'act-h-sayi-oruntuleri',
                  title: '🔢 Sonlu Sayı Örüntüleri ve Genel Kural',
                  category: 'sayi',
                  description: 'Ardışık terimleri arasındaki ortak fark veya oranı inceleyerek örüntünün n. terimini cebirsel olarak ifade edin.',
                  learningGoal: 'Tümevarımsal akıl yürütme ile genel terim bağıntısına ulaşmak.',
                  folderColor: '#10b981',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Sayı doğrusunda adımları takip ederek örüntü kuralını belirleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Sayı örüntülerinin cebirsel genellemesini tamamladınız.',
                },
              ],
            },
          ],
        },

        // 4. TEMA: GEOMETRİK ŞEKİLLER (32 Ders Saati - 5 Çıktı)
        {
          id: 'tymm-h-geometri',
          code: 'MAT.H.4',
          orderNumber: 4,
          themeName: 'Geometrik Şekiller',
          fullTitle: 'MAT.H.4. Geometrik Şekiller',
          category: 'geometri',
          lessonHours: 32,
          outcomeCount: 5,
          description: 'Pergel ve cetvel ile geometrik inşalar, özel dörtgenlerin çıkarımı, fraktallar (Koch kar tanesi, Sierpinski üçgeni), Türk-İslam süsleme ve kaplama sanatı.',
          colorTheme: '#10b981',
          topics: [
            {
              id: 'h-geometrik-insa-ve-fraktal',
              title: 'Geometrik İnşa, Özel Dörtgenler ve Fraktallar',
              code: 'MAT.H.4.1-5',
              category: 'geometri',
              badge: 'İnşa & Fraktal',
              description: 'Pergel-cetvel inşaları (dikme, açıortay, paralel, eşkenar üçgen, düzgün altıgen), özel dörtgenler, fraktal yapıları ve düzlem kaplamaları.',
              learningOutcomes: [
                'Farklı geometrik kavram ve şekillerin inşa çalışmalarında matematiksel araç ve teknolojilerden yararlanabilme.',
                'İnşa edilen özel dörtgenlerin (yamuk, paralelkenar, dikdörtgen, eşkenar dörtgen, kare) özellikleri ile ilgili çıkarım yapabilme.',
                'Fraktalları ve geometrik süslemeleri çözümleyebilme, özgün kaplamalar sentezleyebilme.',
              ],
              activities: [
                {
                  id: 'act-h-pergel-insa',
                  title: '📐 Pergel ve Cetvel ile Geometrik İnşa',
                  category: 'geometri',
                  description: 'Bir doğruya dışındaki noktadan dikme inme, açıya eş açı ve düzgün altıgen inşasını pergel-cetvel kurallarıyla gerçekleştirin.',
                  learningGoal: 'Geometrik inşanın aksiyomatik ve değişmez kurallarını kavramak.',
                  folderColor: '#10b981',
                  previewType: 'circle_radius',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Pergel açıklığını ayarlayarak kesim noktalarını birleştirin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Geometrik inşayı başarıyla tamamladınız.',
                },
                {
                  id: 'act-h-fraktal-dunyasi',
                  title: '❄️ Fraktal Geometrisi (Koch Kar Tanesi & Sierpinski)',
                  category: 'geometri',
                  description: 'Kendini tekrarlayan fraktal desenlerinin iterasyon adımlarını, alan ve çevre değişimlerini modelleyin.',
                  learningGoal: 'Fraktalların oran ve benzerlik yapısını çözümlemek.',
                  folderColor: '#6366f1',
                  previewType: 'transformation_symmetry',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'İterasyon adımlarını artırarak fraktalın oluşumunu inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Fraktalların büyüleyici geometrisini keşfettiniz.',
                },
                {
                  id: 'act-h-susleme-kaplama',
                  title: '🎨 Türk-İslam Süsleme ve Düzlem Kaplama Sanatı',
                  category: 'geometri',
                  description: 'Selçuklu yıldızları, eşkenar üçgen ve düzgün altıgenler ile boşluksuz ve çakışmasız düzlem kaplamaları oluşturun.',
                  learningGoal: 'Düzgün çokgenlerin iç açı toplamı kuralıyla (360°) düzlemi kaplayabilmek.',
                  folderColor: '#f59e0b',
                  previewType: 'pattern_blocks',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Düzgün çokgenleri bir araya getirerek özgün bir kaplama deseni oluşturun.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Süsleme ve kaplama sanatını başarıyla modellediniz.',
                },
              ],
            },
          ],
        },

        // 5. TEMA: İSTATİSTİKSEL ARAŞTIRMA SÜRECİ (6 Ders Saati - 1 Çıktı)
        {
          id: 'tymm-h-istatistik',
          code: 'MAT.H.5',
          orderNumber: 5,
          themeName: 'İstatistiksel Araştırma Süreci',
          fullTitle: 'MAT.H.5. İstatistiksel Araştırma Süreci',
          category: 'istatistik',
          lessonHours: 6,
          outcomeCount: 1,
          description: 'Başkaları tarafından oluşturulan istatistiksel görsel, özet, sonuç, yorum ve tahminlerin eleştirel bir bakış açısıyla tartışılması ve değerlendirilmesi.',
          colorTheme: '#f59e0b',
          topics: [
            {
              id: 'h-istatistiksel-elestirel-bakis',
              title: 'İstatistiksel Sonuç ve Yorumları Eleştirel Değerlendirme',
              code: 'MAT.H.5.1',
              category: 'istatistik',
              badge: 'Eleştirel İstatistik',
              description: 'Yanıltıcı grafikler, eksik ölçekler, yanlı örneklemler ve istatistiksel çıkarımların doğrulanması.',
              learningOutcomes: [
                'Başkaları tarafından oluşturulan istatistiksel sonuç veya yorumları tartışabilme.',
                'İstatistiksel temellendirme yaparak hataları ya da yanlılıkları tespit edebilme.',
              ],
              activities: [
                {
                  id: 'act-h-yaniltici-grafik',
                  title: '📊 Yanıltıcı Grafikler ve İstatistiksel Eleştiri',
                  category: 'istatistik',
                  description: 'Ölçeği sıfırdan başlamayan veya boyutları orantısız verilen grafikleri inceleyerek yanıltıcı algıları tespit edin.',
                  learningGoal: 'Veri görselleştirmelerinde tarafsız ve doğru yorumlama bilinci kazanmak.',
                  folderColor: '#f59e0b',
                  previewType: 'data_barchart',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Verilen grafikteki hata ve yanlılıkları belirleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! İstatistiksel eleştirel değerlendirme sürecini başarıyla tamamladınız.',
                },
              ],
            },
          ],
        },
      ],
      topics: [],
    },

    // =========================================================================
    // 9. SINIF (216 Ders Saati — 20 Öğrenme Çıktısı)
    // =========================================================================
    {
      gradeNumber: 9,
      title: '9. Sınıf',
      subtitle: 'Sayılar, Fonksiyonlar, Geometrik İspat ve Algoritmalar',
      description: 'Gerçek sayılar, doğrusal referans fonksiyonlar ve mutlak değer, üçgende açılar ve eşitsizlik, dönüşümler ve benzerlik (Tales, Öklid, Pisagor), algoritma ve mantık, tek nicel değişkenli istatistik ve deneysel olasılık.',
      themes: [
        {
          id: 'tymm-9-sayilar',
          code: 'MAT.9.1',
          orderNumber: 1,
          themeName: 'Sayılar',
          fullTitle: 'MAT.9.1. Sayılar',
          lessonHours: 38,
          outcomeCount: 4,
          description: 'Gerçek sayıların üslü ve köklü gösterimleri, sayı aralıkları, sayı kümelerinin özellikleri (sıralı olma, arada olma, kapalılık), cebirsel özdeşlikler ve geometrik modelleme.',
          colorTheme: '#8b5cf6',
          topics: [
            {
              id: '9-sayilar-us-kok',
              title: 'Üslü ve Köklü Gösterimlerle Muhakeme',
              code: 'MAT.9.1.1',
              category: 'sayi',
              badge: 'Gerçek Sayılar',
              description: 'Gerçek sayıların üslü ve köklü gösterimleriyle yapılan işlemler, bilimsel gösterim ve yaklaşık değer hesabı.',
              learningOutcomes: [
                'Gerçek sayıların üslü ve köklü gösterimleriyle yapılan işlemlere dair muhakeme yapabilme.',
                'İrrasyonel sayıların yaklaşık değerlerini ve hata payını modelleyebilme.',
              ],
              activities: [
                {
                  id: 'act-9-kok-yaklasik',
                  title: 'Karekökün Sayı Doğrusundaki Yeri ve Yaklaşık Değeri',
                  category: 'sayi',
                  description: 'Karekök içindeki bir sayının ardışık iki tam sayı arasındaki konumunu geometrik olarak keşfedin.',
                  learningGoal: 'İrrasyonel sayıların sayı doğrusundaki yoğunluğunu kavramak.',
                  folderColor: '#8b5cf6',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Sayı doğrusunda √2, √3 ve √5 değerlerinin yerlerini inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Köklü sayıların yaklaşık değer mantığını keşfettiniz.',
                },
                {
                  id: 'act-9-ozdeslik-model',
                  title: 'Cebirsel Özdeşliklerin Alan Modeli',
                  category: 'cebir',
                  description: '(a + b)² = a² + 2ab + b² ve a² - b² = (a-b)(a+b) özdeşliklerini geometrik kare ve dikdörtgen alanlarıyla modelleyin.',
                  learningGoal: 'Cebirsel özdeşliklerin geometrik ispatını kavramak.',
                  folderColor: '#ec4899',
                  previewType: 'triangle_explorer',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'a ve b kenarlarını değiştirerek alanların toplamını inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Özdeşliklerin alan modellemesini tamamladınız.',
                },
              ],
            },
            {
              id: '9-sayi-kumeleri-aralik',
              title: 'Sayı Aralıkları ve Küme Gösterimleri',
              code: 'MAT.9.1.2',
              category: 'sayi',
              badge: 'Kümeler & Aralıklar',
              description: 'Gerçek sayı aralıkları ([a, b], (a, b)), mutlak değer eşitsizlikleri (|x - a| < r) ve küme işlemleri.',
              learningOutcomes: [
                'Gerçek sayı aralıklarının gösteriminde ve işlemlerinde küme sembollerinden yararlanabilme.',
                'Mutlak değer gösterimi ile mesafe ve aralık ilişkisini modelleyebilme.',
              ],
              activities: [
                {
                  id: 'act-9-mutlak-aralik',
                  title: '|x - a| < r Sayı Doğrusu Aralığı Simülatörü',
                  category: 'sayi',
                  description: 'Merkezi a olan r yarıçaplı simetrik aralığı sayı doğrusu üzerinde dinamik kaydırıcılarla gözlemleyin.',
                  learningGoal: 'Mutlak değerli eşitsizliklerin geometrik uzaklık anlamını keşfetmek.',
                  folderColor: '#3b82f6',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Merkez a ve yarıçap r değerlerini değiştirin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Aralık ve mutlak değer ilişkisi başarıyla kavrandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-9-nicelik-degisim',
          code: 'MAT.9.2',
          orderNumber: 2,
          themeName: 'Nicelikler ve Değişimler',
          fullTitle: 'MAT.9.2. Nicelikler ve Değişimler',
          lessonHours: 38,
          outcomeCount: 3,
          description: 'Doğrusal referans fonksiyon f(x)=x ve grafik dönüşümleri g(x)=a·f(x±r)±k, mutlak değer fonksiyonu m(x)=±|ax±b|±c, parçalı fonksiyonlar, doğrusal denklem ve eşitsizlikler, arz-talep modelleri.',
          colorTheme: '#06b6d4',
          topics: [
            {
              id: '9-fonk-dogrusal-donusum',
              title: 'Doğrusal Referans Fonksiyon ve Dönüşümleri',
              code: 'MAT.9.2.1',
              category: 'fonksiyon',
              badge: 'Fonksiyonlar',
              description: 'f(x) = x fonksiyonuna uygulanan öteleme, eğim katsayısı ve simetri dönüşümlerinin nitel özellikleri.',
              learningOutcomes: [
                'Gerçek sayılarda f(x)=x referans fonksiyonundan türetilen g(x)=a·f(x±r)±k doğrusal fonksiyonların nitel özelliklerini muhakeme edebilme.',
                'Artanlık, azalanlık, sıfırları ve birebirliği grafik üzerinden analiz edebilme.',
              ],
              activities: [
                {
                  id: 'act-9-dogrusal-slider',
                  title: 'g(x) = a(x - r) + k Parametre Laboratuvarı',
                  category: 'fonksiyon',
                  description: 'a (eğim), r (yatay öteleme) ve k (dikey öteleme) parametrelerini değiştirerek doğrunun değişimini keşfedin.',
                  learningGoal: 'Katsayıların fonksiyon grafiğine etkisini incelemek.',
                  folderColor: '#06b6d4',
                  previewType: 'slope_line',
                  initialObjects: [],
                  mission: {
                    type: 'slope_explorer',
                    currentSliders: [
                      { name: 'a', label: 'Eğim (a)', min: -4, max: 4, step: 0.5, value: 1 },
                      { name: 'r', label: 'Yatay Öteleme (r)', min: -5, max: 5, step: 1, value: 0 },
                      { name: 'k', label: 'Dikey Öteleme (k)', min: -5, max: 5, step: 1, value: 0 },
                    ],
                  },
                  steps: [{ stepNumber: 1, instruction: 'a=2, r=1, k=3 değerlerini ayarlayarak g(x)=2(x-1)+3 doğrusunu elde edin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Doğrusal dönüşümler başarıyla tamamlandı.',
                },
                {
                  id: 'act-9-mutlak-parcali',
                  title: 'm(x) = |ax + b| Kırılma Noktası ve Parçalı Gösterim',
                  category: 'fonksiyon',
                  description: 'Mutlak değer fonksiyonunun sıfır noktasındaki (V şekli) yön değişimini ve parçalı fonksiyon karşılığını keşfedin.',
                  learningGoal: 'Mutlak değer fonksiyonunu iki doğrusal parçaya ayırmayı kavramak.',
                  folderColor: '#f59e0b',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'x ekseninin altına düşen kısmın yukarı simetriğini inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Mutlak değer fonksiyonunun simetri mantığını keşfettiniz.',
                },
              ],
            },
            {
              id: '9-fonk-isaret-esitsizlik',
              title: 'İşaret Tablosu ve Doğrusal Eşitsizlikler',
              code: 'MAT.9.2.3',
              category: 'cebir',
              badge: 'Denklem & Eşitsizlik',
              description: 'f(x) < 0 ve f(x) ≥ g(x) eşitsizliklerinin grafiksel kesişim ve işaret tablosu yöntemiyle çözümü, piyasa arz-talep dengesi.',
              learningOutcomes: [
                'Doğrusal fonksiyonlarla ifade edilen denklem ve eşitsizlikler içeren problemleri çözebilme.',
                'İki doğrunun kesişim noktasını sistem çözümü olarak yorumlayabilme.',
              ],
              activities: [
                {
                  id: 'act-9-arz-talep',
                  title: 'Piyasa Denge Fiyatı (Arz - Talep Grafiği)',
                  category: 'cebir',
                  description: 'Artan arz doğrusu ile azalan talep doğrusunun kesişiminde piyasa denge noktasını bulun.',
                  learningGoal: 'İki doğrusal denklemin ortak çözümünün gerçek yaşam karşılığını görmek.',
                  folderColor: '#10b981',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Arz ve talep eğrilerini kesiştirerek denge fiyatını bulun.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Ekonomik denge analizi başarıyla tamamlandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-9-geo-sekiller',
          code: 'MAT.9.3',
          orderNumber: 3,
          themeName: 'Geometrik Şekiller',
          fullTitle: 'MAT.9.3. Geometrik Şekiller',
          lessonHours: 12,
          outcomeCount: 1,
          description: 'Üçgende iç açılar toplamı (180°) ve dış açılar toplamı (360°) ispatları, açı-kenar bağıntıları, üçgen eşitsizliği (|b-c| < a < b+c).',
          colorTheme: '#ef4444',
          topics: [
            {
              id: '9-geo-ucgen-bagintilari',
              title: 'Üçgende Açılar ve Üçgen Eşitsizliği',
              code: 'MAT.9.3.1',
              category: 'geometri',
              badge: 'Üçgenler',
              description: 'Büyük açı karşısında büyük kenar bağıntısı, üçgenin kenar oluşturma şartı ve aksiyomatik ispatlar.',
              learningOutcomes: [
                'Üçgende açı ve kenarla ilgili özellikleri ve ilişkileri doğrulayabilme veya ispatlayabilme.',
                'Üçgen eşitsizliğini dinamik geometrik yapılarla test edebilme.',
              ],
              activities: [
                {
                  id: 'act-9-ucgen-esitsizlik',
                  title: 'Dinamik Üçgen Oluşturma Laboratuvarı',
                  category: 'geometri',
                  description: 'Üçgenin köşelerini serbestçe hareket ettirerek |b-c| < a < b+c kuralını ve en büyük açı karşısındaki en uzun kenarı gözlemleyin.',
                  learningGoal: 'Üçgen eşitsizliği ve açı-kenar ilişkisini keşfetmek.',
                  folderColor: '#ef4444',
                  previewType: 'triangle_explorer',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Köşeleri sürükleyerek kenar uzunlukları ve açıları inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Üçgen bağıntıları başarıyla doğrulandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-9-eslik-benzerlik',
          code: 'MAT.9.4',
          orderNumber: 4,
          themeName: 'Eşlik ve Benzerlik',
          fullTitle: 'MAT.9.4. Eşlik ve Benzerlik',
          lessonHours: 36,
          outcomeCount: 5,
          description: 'Geometrik dönüşümler (öteleme, yansıma, dönme), üçgenlerde eşlik ve benzerlik koşulları (K-K-K, A-A, A-K-A), Tales, Öklid ve Pisagor teoremlerinin ispatı.',
          colorTheme: '#f59e0b',
          topics: [
            {
              id: '9-geo-donusumler',
              title: 'Geometrik Dönüşümler ve Eşlik',
              code: 'MAT.9.4.1',
              category: 'geometri',
              badge: 'Dönüşüm Geometrisi',
              description: 'Düzlemde öteleme, doğruya göre yansıma ve dönme merkezi etrafında dönme dönüşümleri.',
              learningOutcomes: [
                'Geometrik dönüşümlerle (yansıma, öteleme, dönme) ilgili çıkarım yapabilme.',
                'Dönüşümler altındaki görüntünün baştaki şekille eş olduğunu kavrayabilme.',
              ],
              activities: [
                {
                  id: 'act-9-donme-merkezi',
                  title: 'Dönme Merkezi ve Açısı Simülasyonu',
                  category: 'geometri',
                  description: 'Bir üçgeni seçilen merkez etrafında θ açısı kadar döndürerek oluşan görüntünün eşliğini inceleyin.',
                  learningGoal: 'Dönme dönüşümünün metrik koruma özelliğini görmek.',
                  folderColor: '#f59e0b',
                  previewType: 'angle_explorer',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Dönme açısını 90° ve 180° yaparak üçgenin yeni konumunu gözlemleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Dönme dönüşümü başarıyla kavrandı.',
                },
              ],
            },
            {
              id: '9-geo-tales-oklid-pisagor',
              title: 'Tales, Öklid ve Pisagor Teoremleri',
              code: 'MAT.9.4.4',
              category: 'geometri',
              badge: 'Klasik Teoremler',
              description: 'Paralel doğruların ayırdığı orantılı parçalar (Tales), dik üçgende hipotenüs yüksekliği bağıntıları (Öklid) ve Pisagor teoremi.',
              learningOutcomes: [
                'Tales, Öklid ve Pisagor teoremlerini benzer üçgenler yardımıyla ispatlayabilme.',
                'Teoremleri gerçek yaşam ve mimari mühendislik problemlerine uyarlayabilme.',
              ],
              activities: [
                {
                  id: 'act-9-oklid-insa',
                  title: 'Öklid Yükseklik ve Kenar Bağıntıları (h² = p·k)',
                  category: 'geometri',
                  description: 'Dik üçgende hipotenüse indirilen dikmenin ayırdığı parçalarla h² = p·k, b² = k·a, c² = p·a bağıntılarını dinamik olarak test edin.',
                  learningGoal: 'Öklid bağıntılarının benzerlikten türeyişini kavramak.',
                  folderColor: '#3b82f6',
                  previewType: 'triangle_explorer',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Dik köşeden hipotenüse dikme indirin ve p, k uzunluklarını ölçün.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Öklid bağıntıları başarıyla ispatlandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-9-algoritma-bilisim',
          code: 'MAT.9.5',
          orderNumber: 5,
          themeName: 'Algoritma ve Bilişim',
          fullTitle: 'MAT.9.5. Algoritma ve Bilişim',
          lessonHours: 30,
          outcomeCount: 3,
          description: 'Algoritma temelli problem çözme, Eratosthenes asal kalburu, ikili arama, akış şemaları, sözde kod, ikili sistem binary, Königsberg köprüsü ve çizge (graf) kuramı.',
          colorTheme: '#10b981',
          topics: [
            {
              id: '9-bilisim-algoritma-cizge',
              title: 'Algoritmik Düşünme ve Çizge Kuramı',
              code: 'MAT.9.5.1',
              category: 'cebir',
              badge: 'Bilişim & Mantık',
              description: 'Königsberg 7 köprü problemi, düğüm ve ayrıtlar, en kısa yol algoritmaları ve mantık bağlaçları.',
              learningOutcomes: [
                'Algoritma temelli yaklaşımlarla problem çözebilme (akış şeması, sözde kod, çizge).',
                'Mantık bağlaçları (ve, veya, ya da, ise) ve niceleyicilerin (her, bazı) algoritmik yapılarını çözümleyebilme.',
              ],
              activities: [
                {
                  id: 'act-9-cizge-konigsberg',
                  title: 'Königsberg Köprüleri ve Tek Çizgide Çizim (Euler Turu)',
                  category: 'cebir',
                  description: 'Düğümlerin derecelerine bakarak bir şeklin el kaldırmadan tek seferde çizilip çizilemeyeceğini keşfedin.',
                  learningGoal: 'Çizge kuramında Euler devresi mantığını anlamak.',
                  folderColor: '#10b981',
                  previewType: 'spatial_grid',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Tüm ayrıtlardan yalnızca bir kez geçerek turu tamamlayın.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Çizge kuramı algoritması başarıyla çözüldü.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-9-istatistik',
          code: 'MAT.9.6',
          orderNumber: 6,
          themeName: 'İstatistiksel Araştırma Süreci',
          fullTitle: 'MAT.9.6. İstatistiksel Araştırma Süreci',
          lessonHours: 34,
          outcomeCount: 2,
          description: 'Tek nicel değişkenli veri dağılımları, nokta grafiği, histogram, kutu grafiği, standart sapma, çeyrekler açıklığı ve değişebilirlik türleri.',
          colorTheme: '#6366f1',
          topics: [
            {
              id: '9-ist-nicel-veri',
              title: 'Tek Nicel Değişkenli Veri Dağılımları',
              code: 'MAT.9.6.1',
              category: 'istatistik',
              badge: 'Veri Analizi',
              description: 'Kutu grafiğinde çeyrekler (Q1, Q2, Q3), aykırı değerler ve standart sapmanın dağılım yayılımındaki rolü.',
              learningOutcomes: [
                'Tek nicel değişkenli veri dağılımları ile çalışabilme ve veriye dayalı karar verebilme.',
                'Histogram ve kutu grafiği kullanarak verilerin simetrisini ve yayılımını yorumlayabilme.',
              ],
              activities: [
                {
                  id: 'act-9-kutu-grafigi',
                  title: 'Kutu Grafiği (Box-Plot) ve Çeyrekler Simülasyonu',
                  category: 'istatistik',
                  description: 'Veri setini değiştirerek min, Q1, medyan (Q2), Q3 ve max sınırlarının nasıl değiştiğini inceleyin.',
                  learningGoal: 'Kutu grafiğinde 5 sayılı özeti ve çeyrekler açıklığını kavramak.',
                  folderColor: '#6366f1',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Veri değerlerini kaydırarak çeyrekler açıklığını gözlemleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Kutu grafiği analizi başarıyla tamamlandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-9-olasilik',
          code: 'MAT.9.7',
          orderNumber: 7,
          themeName: 'Veriden Olasılığa',
          fullTitle: 'MAT.9.7. Veriden Olasılığa',
          lessonHours: 18,
          outcomeCount: 2,
          description: '2-3 olaylı deneyler, deneysel ve teorik olasılık, Büyük Sayılar Yasası simülasyonu, ayrık ve ayrık olmayan olaylar.',
          colorTheme: '#ec4899',
          topics: [
            {
              id: '9-olas-deneysel-teorik',
              title: 'Deneysel ve Teorik Olasılık',
              code: 'MAT.9.7.1',
              category: 'olasilik',
              badge: 'Büyük Sayılar Yasası',
              description: 'Deney tekrar sayısı arttıkça göreli sıklıkların teorik olasılığa yaklaşması (Büyük Sayılar Yasası).',
              learningOutcomes: [
                'Olayların olasılığını deney yaparak tahmin edebilme ve teorik olasılıkla karşılaştırabilme.',
                'Ayrık ve ayrık olmayan olayların birleşim olasılığını P(A∪B)=P(A)+P(B)-P(A∩B) ile hesaplayabilme.',
              ],
              activities: [
                {
                  id: 'act-9-zar-simulasyon',
                  title: 'Büyük Sayılar Yasası — 1000 Zar Atma Deneyi',
                  category: 'olasilik',
                  description: 'İki zar atıldığında toplamın 7 gelme olasılığını 10, 100, 500 ve 1000 atışta gözlemleyerek 1/6 (≈%16.6) teorik değerine yakınsayışını izleyin.',
                  learningGoal: 'Deney sayısı arttıkça deneysel olasılığın teorik olasılığa eşitlendiğini görmek.',
                  folderColor: '#ec4899',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Atış sayısını artırarak göreli sıklık grafiğini inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Büyük Sayılar Yasası başarıyla doğrulandı.',
                },
              ],
            },
          ],
        },
      ],
      topics: [],
    },

    // =========================================================================
    // 10. SINIF (216 Ders Saati — 21 Öğrenme Çıktısı)
    // =========================================================================
    {
      gradeNumber: 10,
      title: '10. Sınıf',
      subtitle: 'Trigonometri, Karesel Fonksiyonlar, Sayma ve Analitik Geometri',
      description: 'Dik üçgende trigonometri ve sinüs/kosinüs teoremleri, iki kategorik değişkenli istatistik, asal çarpanlar ve EBOB/EKOK, paraboller ve karekök fonksiyonları, faktöriyel-kombinasyon ve Pascal üçgeni, doğrunun analitiği ve Bayes olasılık teoremi.',
      themes: [
        {
          id: 'tymm-10-geo-sekiller',
          code: 'MAT.10.1',
          orderNumber: 1,
          themeName: 'Geometrik Şekiller',
          fullTitle: 'MAT.10.1. Geometrik Şekiller (Trigonometri & Teoremler)',
          lessonHours: 36,
          outcomeCount: 4,
          description: 'Dik üçgende trigonometrik oranlar, birim çember, üçgenin yardımcı elemanları (açıortay, kenarortay/ağırlık merkezi G, kenar orta dikme/çevrel çember, yükseklik/diklik merkezi), sinüs ve kosinüs teoremleri.',
          colorTheme: '#8b5cf6',
          topics: [
            {
              id: '10-trig-oran-birim-cember',
              title: 'Birim Çember ve Trigonometrik Oranlar',
              code: 'MAT.10.1.1',
              category: 'trigonometri',
              badge: 'Trigonometri',
              description: 'Birim çember üzerinde yönlü açılar, (cos θ, sin θ) koordinatları, tanjant-kotanjant eksenleri ve sin²θ + cos²θ = 1 özdeşliği.',
              learningOutcomes: [
                'Dik üçgende trigonometrik oranlara ve temel trigonometrik özdeşliklere ilişkin çıkarım yapabilme.',
                'Geniş açıların trigonometrik oranlarını birim çember üzerinden modelleyebilme.',
              ],
              activities: [
                {
                  id: 'act-10-birim-cember',
                  title: 'Dinamik Birim Çember ve Yönlü Açılar',
                  category: 'trigonometri',
                  description: 'Açı kolunu 0°-360° döndürerek (x, y) = (cos θ, sin θ) değerlerinin değişimini ve 4 bölgedeki işaretlerini inceleyin.',
                  learningGoal: 'Trigonometrik fonksiyonların birim çemberdeki geometrik anlamını kavramak.',
                  folderColor: '#8b5cf6',
                  previewType: 'circle_radius',
                  initialObjects: [],
                  mission: {
                    type: 'angle_explorer',
                  },
                  steps: [{ stepNumber: 1, instruction: 'Açıyı 30°, 45°, 60°, 120° ve 240° değerlerine getirip sinüs ve kosinüs değerlerini okuyun.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Birim çember trigonometrisi başarıyla kavrandı.',
                },
              ],
            },
            {
              id: '10-geo-yardimci-elemanlar',
              title: 'Üçgenin Yardımcı Elemanları ve Merkezleri',
              code: 'MAT.10.1.2',
              category: 'geometri',
              badge: 'Üçgen Merkezleri',
              description: 'İç açıortaylar (İç teğet çember merkezi), Kenarortaylar (Ağırlık merkezi G, 2:1 oranı), Kenar orta dikmeler (Çevrel çember merkezi), Yükseklikler (Diklik merkezi).',
              learningOutcomes: [
                'Üçgenin yardımcı elemanlarının özelliklerine ve kesim noktalarına dair çıkarım yapabilme.',
                'Ağırlık merkezinin kenarortayı 2:1 oranında böldüğünü geometrik olarak doğrulayabilme.',
              ],
              activities: [
                {
                  id: 'act-10-agirlik-merkezi',
                  title: 'Kenarortaylar ve Ağırlık Merkezi (G Noktası)',
                  category: 'geometri',
                  description: 'Üçgenin 3 kenarortayının tek bir G noktasında kesiştiğini ve köşeye 2k, kenara 1k uzaklıkta olduğunu gözlemleyin.',
                  learningGoal: 'Ağırlık merkezinin 2:1 kuralını ve dengelenme noktasını keşfetmek.',
                  folderColor: '#3b82f6',
                  previewType: 'triangle_explorer',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Üçgenin köşelerini sürükleyerek G noktasının konumunu inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Ağırlık merkezi özellikleri başarıyla incelendi.',
                },
              ],
            },
            {
              id: '10-geo-sin-cos-teoremleri',
              title: 'Sinüs ve Kosinüs Teoremleri',
              code: 'MAT.10.1.4',
              category: 'trigonometri',
              badge: 'Teoremler',
              description: 'a² = b² + c² - 2bc·cos(A) kosinüs teoremi ve a/sin(A) = b/sin(B) = c/sin(C) = 2R sinüs teoremi.',
              learningOutcomes: [
                'Sinüs ve kosinüs teoremlerini doğrulayabilme veya ispatlayabilme.',
                'Rastgele üçgenlerde bilinmeyen kenar ve açıları trigonometrik teoremlerle hesaplayabilme.',
              ],
              activities: [
                {
                  id: 'act-10-kosinus-teoremi',
                  title: 'Kosinüs Teoremi — Genişletilmiş Pisagor',
                  category: 'trigonometri',
                  description: 'A açısı 90° iken Pisagor (a² = b² + c²), dar açı iken a² < b² + c², geniş açı iken a² > b² + c² olduğunu ve -2bc·cos(A) teriminin etkisini keşfedin.',
                  learningGoal: 'Kosinüs teoreminin Pisagor ile ilişkisini kavramak.',
                  folderColor: '#f59e0b',
                  previewType: 'triangle_explorer',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'A açısını değiştirerek a² ile b²+c²-2bc·cos(A) eşitliğini doğrulayın.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Kosinüs teoremi başarıyla doğrulandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-10-istatistik',
          code: 'MAT.10.2',
          orderNumber: 2,
          themeName: 'İstatistiksel Araştırma Süreci',
          fullTitle: 'MAT.10.2. İstatistiksel Araştırma Süreci (İki Kategorik Değişken)',
          lessonHours: 24,
          outcomeCount: 2,
          description: 'İki kategorik değişkenli veriler, iki yönlü çapraz tablo, koşullu göreli sıklıklar, kümeli sütun grafikleri, ilişkililik ve neden-sonuç ayrımı.',
          colorTheme: '#06b6d4',
          topics: [
            {
              id: '10-ist-iki-kategorik',
              title: 'İki Yönlü Tablolar ve Koşullu Göreli Sıklıklar',
              code: 'MAT.10.2.1',
              category: 'istatistik',
              badge: 'Çapraz Tablo',
              description: 'İki kategorik değişken arasındaki ilişkililiğin satır ve sütun yüzdeleri ile analizi.',
              learningOutcomes: [
                'İki kategorik değişkenli veri ile çalışabilme ve ilişkililiğe dayalı karar verebilme.',
                'Korelasyon ile neden-sonuç ilişkisinin farklı olduğunu kavrayabilme.',
              ],
              activities: [
                {
                  id: 'act-10-capraz-tablo',
                  title: 'İki Yönlü Sıklık Tablosu ve Kümeli Sütun Grafiği',
                  category: 'istatistik',
                  description: 'Verilen veri setinde kategorik değişkenlerin koşullu sıklıklarını hesaplayıp kümeli sütun grafiğinde karşılaştırın.',
                  learningGoal: 'İki kategorik değişkenin birlikte dağılımını yorumlamak.',
                  folderColor: '#06b6d4',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Satır ve sütun toplamlarından koşullu oranları elde edin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! İki yönlü tablo analizi tamamlandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-10-sayilar',
          code: 'MAT.10.3',
          orderNumber: 3,
          themeName: 'Sayılar',
          fullTitle: 'MAT.10.3. Sayılar (Asal Çarpanlar, EBOB-EKOK ve Bölünebilme)',
          lessonHours: 20,
          outcomeCount: 3,
          description: 'Doğal sayıların asal çarpanları, pozitif bölen sayısı, EBOB-EKOK özellikleri (a·b = EBOB·EKOK), basamak çözümlemesiyle bölünebilme kuralları ve kalan algoritmaları.',
          colorTheme: '#10b981',
          topics: [
            {
              id: '10-sayilar-ebob-ekok',
              title: 'EBOB, EKOK ve Asal Çarpanlar',
              code: 'MAT.10.3.2',
              category: 'sayi',
              badge: 'Sayılar Teorisi',
              description: 'Aralarında asal sayılar, ortak bölen ve ortak kat özellikleri, en küçük ortak kat ile periyodik durumlar.',
              learningOutcomes: [
                'Birden çok doğal sayının ortak bölenleri ve ortak katları arasındaki ilişkilere dair muhakeme yapabilme.',
                'Bölünebilme kurallarını basamak çözümlemesiyle ispatlayabilme.',
              ],
              activities: [
                {
                  id: 'act-10-ebob-ekok-gorsel',
                  title: 'Öklid EBOB Algoritması ve Geometrik Kare Kaplama',
                  category: 'sayi',
                  description: 'a × b boyutundaki bir dikdörtgeni en büyük karelerle bölerek EBOB(a, b) değerini görsel olarak bulun.',
                  learningGoal: 'Öklid bölme algoritmasının geometrik anlamını keşfetmek.',
                  folderColor: '#10b981',
                  previewType: 'prism_volume',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Dikdörtgenin içine sığan en büyük kareleri yerleştirin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Öklid EBOB algoritması başarıyla tamamlandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-10-nicelik-degisim',
          code: 'MAT.10.4',
          orderNumber: 4,
          themeName: 'Nicelikler ve Değişimler',
          fullTitle: 'MAT.10.4. Nicelikler ve Değişimler (Karesel, Karekök, Rasyonel Fonksiyonlar & Parabol)',
          lessonHours: 58,
          outcomeCount: 6,
          description: 'Fonksiyon olma şartları, karesel referans fonksiyon f(x)=x² ve parabol dönüşümleri g(x)=a(x±r)²±k, tepe noktası T(-b/2a, k), simetri ekseni, karekök f(x)=√x, rasyonel f(x)=1/x, ters fonksiyon ve optimizasyon problemleri.',
          colorTheme: '#ec4899',
          topics: [
            {
              id: '10-fonk-parabol-donusum',
              title: 'Karesel Fonksiyonlar ve Parabolün Geometrisi',
              code: 'MAT.10.4.2',
              category: 'fonksiyon',
              badge: 'Parabol',
              description: 'g(x) = a(x - r)² + k tepe noktası T(r, k), simetri ekseni x = r, kolların yönü ve maksimum/minimum değerler.',
              learningOutcomes: [
                'Gerçek sayılarda f(x)=x² karesel referans fonksiyondan türetilen fonksiyonların nitel özelliklerini muhakeme edebilme.',
                'Parabolün tepe noktasını ve simetri eksenini tamkareye tamamlama yöntemiyle belirleyebilme.',
              ],
              activities: [
                {
                  id: 'act-10-parabol-lab',
                  title: 'Parabol Tepe Noktası T(r, k) ve Açıklık (a) Laboratuvarı',
                  category: 'fonksiyon',
                  description: 'a, r ve k parametrelerini değiştirerek parabolün tepe noktasını, simetri eksenini ve en büyük/en küçük değerini gözlemleyin.',
                  learningGoal: 'Karesel fonksiyon dönüşümlerini ve tepe noktası formunu kavramak.',
                  folderColor: '#ec4899',
                  previewType: 'slope_line',
                  initialObjects: [],
                  mission: {
                    type: 'slope_explorer',
                    currentSliders: [
                      { name: 'a', label: 'Katsayı (a)', min: -3, max: 3, step: 0.5, value: 1 },
                      { name: 'r', label: 'Tepe X (r)', min: -4, max: 4, step: 1, value: 0 },
                      { name: 'k', label: 'Tepe Y (k)', min: -4, max: 4, step: 1, value: 0 },
                    ],
                  },
                  steps: [{ stepNumber: 1, instruction: 'a=1, r=2, k=-3 yaparak tepe noktası (2, -3) olan parabolü oluşturun.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Parabol dönüşümleri başarıyla kavrandı.',
                },
                {
                  id: 'act-10-ters-fonksiyon',
                  title: 'Ters Fonksiyon ve y = x Doğrusuna Göre Simetri',
                  category: 'fonksiyon',
                  description: 'Birebir ve örten f(x) fonksiyonu ile tersi f⁻¹(x) fonksiyonunun y = x birinci açıortay doğrusuna göre simetrik olduğunu keşfedin.',
                  learningGoal: 'Ters fonksiyonun grafiksel simetrisini görmek.',
                  folderColor: '#8b5cf6',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'f(x) üzerindeki (a, b) noktasının f⁻¹(x) üzerinde (b, a) noktasına dönüştüğünü inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Ters fonksiyon simetrisi başarıyla doğrulandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-10-sayma-algoritma',
          code: 'MAT.10.5',
          orderNumber: 5,
          themeName: 'Sayma, Algoritma ve Bilişim',
          fullTitle: 'MAT.10.5. Sayma, Algoritma ve Bilişim (Kombinatorik & Pascal Üçgeni)',
          lessonHours: 28,
          outcomeCount: 2,
          description: 'Eşleştirme, toplama ve çarpma yoluyla sayma, faktöriyel (n!), sıralama sayısı (permütasyon), seçme sayısı (kombinasyon C(n,r)), Pascal üçgeni (Ömer Hayyam), Güvercin Yuvası İlkesi, fonksiyon sıfırlarını bulma algoritmaları.',
          colorTheme: '#f59e0b',
          topics: [
            {
              id: '10-sayma-kombinasyon-pascal',
              title: 'Seçme Sayısı (Kombinasyon) ve Pascal Üçgeni',
              code: 'MAT.10.5.1',
              category: 'cebir',
              badge: 'Kombinatorik',
              description: 'C(n, r) kombinasyon hesabı, Pascal üçgenindeki simetriler, satır toplamları (2ⁿ) ve Ömer Hayyam bağlantısı.',
              learningOutcomes: [
                'Sayma stratejileri (sıralama ve seçme) kullanarak problem çözebilme.',
                'Pascal üçgenindeki cebirsel ve sayısal örüntüleri modelleyebilme.',
              ],
              activities: [
                {
                  id: 'act-10-pascal-ucgeni',
                  title: 'Pascal & Hayyam Üçgeni Örüntü Kaşifi',
                  category: 'cebir',
                  description: 'Pascal üçgeninin satırlarındaki simetriyi C(n, r) = C(n, n-r), satır toplamlarını ve Fibonacci diyagonallerini inceleyin.',
                  learningGoal: 'Kombinasyon katsayılarının geometrik yerleşimini kavramak.',
                  folderColor: '#f59e0b',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Satır toplamlarının 2ⁿ olduğunu doğrulayın.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Pascal üçgeni keşfi başarıyla tamamlandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-10-analitik',
          code: 'MAT.10.6',
          orderNumber: 6,
          themeName: 'Analitik İnceleme',
          fullTitle: 'MAT.10.6. Analitik İnceleme (Nokta ve Doğrunun Analitiği)',
          lessonHours: 22,
          outcomeCount: 2,
          description: 'İki nokta arası uzaklık formülü, doğru parçasını belli oranda içten/dıştan bölen nokta, orta nokta ve ağırlık merkezi, doğrunun eğim açısı α, eğim m=tanα, paralel doğrular (m₁=m₂), dik kesişen doğrular (m₁·m₂=-1).',
          colorTheme: '#3b82f6',
          topics: [
            {
              id: '10-analitik-nokta-dogru',
              title: 'Noktanın ve Doğrunun Analitik İncelenmesi',
              code: 'MAT.10.6.1',
              category: 'geometri',
              badge: 'Analitik Geometri',
              description: 'İki nokta arası uzaklık d = √((x₂-x₁)² + (y₂-y₁)²), eğim m = (y₂-y₁)/(x₂-x₁) ve dik doğruların eğim çarpımı.',
              learningOutcomes: [
                'Dik koordinat sisteminde iki nokta arasındaki uzaklık ve doğru parçasını bölen noktalarla ilgili çıkarım yapabilme.',
                'Dik kesişen doğruların eğimleri çarpımının -1 olduğunu ispatlayabilme.',
              ],
              activities: [
                {
                  id: 'act-10-dik-dogrular-egim',
                  title: 'Dik Doğrular ve Eğim Çarpımı (m₁ · m₂ = -1)',
                  category: 'geometri',
                  description: 'Koordinat düzleminde iki doğruyu birbirine dik konuma getirerek eğimlerinin çarpımının daima -1 olduğunu dinamik olarak gözlemleyin.',
                  learningGoal: 'Analitik düzlemde diklik ve eğim ilişkisini keşfetmek.',
                  folderColor: '#3b82f6',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'm₁ = 2 olan doğruya dik olan doğrunun eğiminin m₂ = -1/2 olduğunu kontrol edin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Dik doğruların analitik kuralı başarıyla doğrulandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-10-olasilik-bayes',
          code: 'MAT.10.7',
          orderNumber: 7,
          themeName: 'Veriden Olasılığa',
          fullTitle: 'MAT.10.7. Veriden Olasılığa (Koşullu Olasılık & Bayes Teoremi)',
          lessonHours: 18,
          outcomeCount: 2,
          description: 'Bağımlı ve bağımsız olaylar, koşullu olasılık P(A|B) = P(A∩B)/P(B), Bayes Teoremi, tıbbi test doğruluk oranları, risk analizleri, ağaç şeması ve alan modeli.',
          colorTheme: '#ef4444',
          topics: [
            {
              id: '10-olas-kosullu-bayes',
              title: 'Koşullu Olasılık ve Bayes Teoremi',
              code: 'MAT.10.7.2',
              category: 'olasilik',
              badge: 'Bayes Teoremi',
              description: 'Tıbbi tanı testlerinde yalancı pozitiflik oranları ve Bayes formülüyle güncellenen olasılıklar.',
              learningOutcomes: [
                'Bir olayın gerçekleşmesinin diğer bir olaya bağlı olduğu koşullu olasılık durumlarını modelleyebilme.',
                'Bayes teoremini kullanarak tıbbi tarama ve risk analizlerinde ileriye yönelik yargıda bulunabilme.',
              ],
              activities: [
                {
                  id: 'act-10-bayes-agac',
                  title: 'Ağaç Şeması ile Bayes Teoremi ve Tıbbi Test Simülatörü',
                  category: 'olasilik',
                  description: 'Hastalık görülme sıklığı, testin duyarlılığı ve özgüllüğü parametrelerini girerek test pozitif çıktığında gerçekten hasta olma olasılığını P(H|+) hesaplayın.',
                  learningGoal: 'Bayes teoreminin karar verme ve tıbbi teşhisteki kritik önemini kavramak.',
                  folderColor: '#ef4444',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Ağaç şemasındaki dalları takip ederek koşullu olasılığı hesaplayın.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Bayes teoremi başarıyla modellendi.',
                },
              ],
            },
          ],
        },
      ],
      topics: [],
    },

    // =========================================================================
    // 11. SINIF (216 Ders Saati — 15 Öğrenme Çıktısı)
    // =========================================================================
    {
      gradeNumber: 11,
      title: '11. Sınıf',
      subtitle: 'İki Değişkenli İstatistik, Çokgenler, Trigonometri, Üstel-Logaritma ve Bileşke',
      description: 'İki nicel değişkenli istatistik (korelasyon), çokgenler ve özel dörtgenler (yamuk, paralelkenar, eşkenar dörtgen, dikdörtgen, kare, deltoid), trigonometrik fonksiyonlar ve periyot, üstel ve logaritmik fonksiyonlar (doğal taban e, pH, deprem Richter), fonksiyonların bileşkesi ve dört işlem.',
      themes: [
        {
          id: 'tymm-11-istatistik',
          code: 'MAT.11.1',
          orderNumber: 1,
          themeName: 'İstatistiksel Araştırma Süreci',
          fullTitle: 'MAT.11.1. İstatistiksel Araştırma Süreci (İki Nicel Değişken & Korelasyon)',
          lessonHours: 24,
          outcomeCount: 2,
          description: 'İki nicel değişkenli veri dağılımları, serpme diyagramı (saçılım grafiği), bölgelere göre sayım oranı, korelasyon katsayısı (yön ve güç: pozitif/negatif, zayıf/orta/güçlü), aykırı değerler.',
          colorTheme: '#6366f1',
          topics: [
            {
              id: '11-ist-sacilim-korelasyon',
              title: 'Serpme Diyagramı ve Korelasyon Katsayısı',
              code: 'MAT.11.1.1',
              category: 'istatistik',
              badge: 'Korelasyon',
              description: 'İki değişken arasındaki doğrusal ilişkinin yönü (pozitif/negatif) ve gücü (r değeri).',
              learningOutcomes: [
                'İki nicel değişkenli veri ile çalışabilme ve korelasyon katsayısına dayalı karar verebilme.',
                'Korelasyonun neden-sonuç ilişkisi anlamına gelmediğini örneklerle değerlendirebilme.',
              ],
              activities: [
                {
                  id: 'act-11-korelasyon-sacilim',
                  title: 'Dinamik Saçılım Grafiği ve Korelasyon Sezgisi',
                  category: 'istatistik',
                  description: 'Noktaları sürükleyerek pozitif korelasyon (r ≈ +0.9), negatif korelasyon (r ≈ -0.8) ve ilişkisiz (r ≈ 0) durumları oluşturun.',
                  learningGoal: 'Korelasyon katsayısının geometrik saçılım karşılığını kavramak.',
                  folderColor: '#6366f1',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Noktaları artan bir doğru boyunca hizalayarak pozitif korelasyonu gözlemleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Korelasyon analizi başarıyla tamamlandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-11-geo-cokgen-dortgen',
          code: 'MAT.11.2',
          orderNumber: 2,
          themeName: 'Geometrik Şekiller',
          fullTitle: 'MAT.11.2. Geometrik Şekiller (Çokgenler & Özel Dörtgenler)',
          lessonHours: 62,
          outcomeCount: 5,
          description: 'Dışbükey ve içbükey çokgenler, iç açılar toplamı (n-2)·180°, dış açılar toplamı 360°, köşegen sayısı, düzgün çokgenler (beşgen, altıgen, sekizgen, onikigen), özel dörtgenler (yamuk, paralelkenar, eşkenar dörtgen, dikdörtgen, kare, deltoid) ve alan bağıntıları.',
          colorTheme: '#10b981',
          topics: [
            {
              id: '11-geo-dortgen-ozel',
              title: 'Özel Dörtgenler Hiyerarşisi ve Alan Bağıntıları',
              code: 'MAT.11.2.2',
              category: 'geometri',
              badge: 'Özel Dörtgenler',
              description: 'Yamuk, paralelkenar, eşkenar dörtgen, dikdörtgen, kare ve deltoid arasındaki hiyerarşik ilişkiler ve köşegen özellikleri.',
              learningOutcomes: [
                'Özel dörtgenlerin kenar, açı, köşegen ve simetri özelliklerinden hareketle aralarındaki ilişkileri yapılandırabilme.',
                'Dörtgenin alanının köşegen uzunlukları ve aradaki açının sinüsüyle A = 1/2·e·f·sin(θ) bağıntısını ispatlayabilme.',
              ],
              activities: [
                {
                  id: 'act-11-dortgen-alan-sinus',
                  title: 'Köşegenler ile Dörtgen Alanı: A = ½ · e · f · sin(θ)',
                  category: 'geometri',
                  description: 'Dörtgenin köşegen uzunluklarını ve aralarındaki açıyı değiştirerek alan değişimini dinamik olarak hesaplayın.',
                  learningGoal: 'Köşegen dik olduğunda alanın (e·f)/2 olduğunu görmek.',
                  folderColor: '#10b981',
                  previewType: 'triangle_explorer',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Köşegenler arasındaki açıyı 90° yaparak eşkenar dörtgen ve deltoid alanını test edin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Dörtgen alan bağıntısı başarıyla kanıtlandı.',
                },
              ],
            },
            {
              id: '11-geo-duzgun-cokgen',
              title: 'Düzgün Çokgenler ve Simetri Eksenleri',
              code: 'MAT.11.2.4',
              category: 'geometri',
              badge: 'Düzgün Çokgenler',
              description: 'Düzgün beşgen, altıgen ve sekizgende bir iç açı (n-2)·180°/n, bir dış açı 360°/n, simetri eksenleri ve alan formülleri.',
              learningOutcomes: [
                'Dışbükey çokgenlerin kenar, açı, köşegen, simetri ve alan özelliklerine dair çıkarım yapabilme.',
                'Düzgün altıgenin 6 eşkenar üçgenden oluştuğunu ve alanını modelleyebilme.',
              ],
              activities: [
                {
                  id: 'act-11-altigen-alan',
                  title: 'Düzgün Altıgenin 6 Eşkenar Üçgenle Modellenmesi',
                  category: 'geometri',
                  description: 'Bir kenarı a olan düzgün altıgeni merkezinden 6 eşkenar üçgene bölerek A = 6·(a²√3/4) alan formülünü keşfedin.',
                  learningGoal: 'Düzgün çokgen alanlarının üçgenlerle parçalanışını anlamak.',
                  folderColor: '#f59e0b',
                  previewType: 'triangle_explorer',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Merkezden köşelere yarıçaplar çizerek 6 eşkenar üçgeni inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Düzgün çokgen alanı başarıyla modellendi.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-11-trigonometrik-fonk',
          code: 'MAT.11.3.1',
          orderNumber: 3,
          themeName: 'Nicelikler ve Değişimler (1) — Trigonometrik Fonksiyonlar',
          fullTitle: 'MAT.11.3 (1). Trigonometrik Fonksiyonlar ve Denklemler',
          lessonHours: 42,
          outcomeCount: 2,
          description: 'Trigonometrik referans fonksiyonlar (sin, cos, tan, cot), periyot T, teklik-çiftlik, grafik dönüşümleri g(x)=k·f(mx±r)±s, trigonometrik denklemler ve harmonik hareket/salınım modellemeleri.',
          colorTheme: '#8b5cf6',
          topics: [
            {
              id: '11-trig-fonk-grafik',
              title: 'Trigonometrik Fonksiyon Grafikleri ve Periyot',
              code: 'MAT.11.3.1',
              category: 'trigonometri',
              badge: 'Periyodik Değişim',
              description: 'y = sin(x) ve y = cos(x) dalgaları, periyot T = 2π/|m|, genlik k ve faz kayması.',
              learningOutcomes: [
                'Trigonometrik referans fonksiyonların nitel özelliklerini (tanım/görüntü kümesi, artanlık/azalanlık, periyot) belirleyebilme.',
                'Trigonometrik denklemlerle basit harmonik hareket ve dönme dolap problemlerini çözebilme.',
              ],
              activities: [
                {
                  id: 'act-11-sinus-dalgasi',
                  title: 'y = k · sin(mx + r) Dalga & Genlik Simülatörü',
                  category: 'trigonometri',
                  description: 'k (genlik) ve m (frekans/periyot) parametrelerini değiştirerek sinüs dalgasının genleşip sıkışmasını gözlemleyin.',
                  learningGoal: 'Trigonometrik dalgaların periyot ve genlik dönüşümlerini kavramak.',
                  folderColor: '#8b5cf6',
                  previewType: 'slope_line',
                  initialObjects: [],
                  mission: {
                    type: 'slope_explorer',
                    currentSliders: [
                      { name: 'k', label: 'Genlik (k)', min: 0.5, max: 4, step: 0.5, value: 1 },
                      { name: 'm', label: 'Frekans Katsayısı (m)', min: 0.5, max: 4, step: 0.5, value: 1 },
                    ],
                  },
                  steps: [{ stepNumber: 1, instruction: 'k=2 ve m=2 yaparak genliği 2 katına çıkan, periyodu π olan dalgayı elde edin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Trigonometrik dalga dönüşümleri kavrandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-11-ustel-logaritma',
          code: 'MAT.11.3.2',
          orderNumber: 4,
          themeName: 'Nicelikler ve Değişimler (2) — Üstel ve Logaritmik Fonksiyonlar',
          fullTitle: 'MAT.11.3 (2). Üstel ve Logaritmik Fonksiyonlar',
          lessonHours: 42,
          outcomeCount: 4,
          description: 'Üstel referans fonksiyon f(x)=aˣ, doğal taban e ve f(x)=eˣ, logaritmik fonksiyon f(x)=logₐ(x), doğal logaritma ln(x), y=x doğrusuna göre simetri ve ters fonksiyon ilişkisi, Richter deprem ölçeği, desibel ses seviyesi, pH değeri ve karbon-14 yaş tayini.',
          colorTheme: '#ec4899',
          topics: [
            {
              id: '11-ustel-log-ters',
              title: 'Üstel Fonksiyon, e Sayısı ve Logaritma',
              code: 'MAT.11.3.4',
              category: 'fonksiyon',
              badge: 'Logaritma',
              description: 'y = aˣ ile y = logₐ(x) arasındaki ters fonksiyon ilişkisi, log(x·y) = log(x) + log(y) ve taban değiştirme.',
              learningOutcomes: [
                'Üstel fonksiyonların ters fonksiyonlarını inceleyerek logaritmik fonksiyona dair çıkarım yapabilme.',
                'Gerçek yaşam durumlarında üstel ve logaritmik denklem ve eşitsizlikleri çözebilme.',
              ],
              activities: [
                {
                  id: 'act-11-richter-deprem',
                  title: 'Richter Deprem Şiddeti ve pH Logaritmik Modeli',
                  category: 'fonksiyon',
                  description: 'Richter ölçeğinde her 1 birimlik artışın genlikte 10 kat, enerjide ≈31.6 kat artış anlamına geldiğini logaritmik grafikle inceleyin.',
                  learningGoal: 'Logaritmanın büyük sayı aralıklarını ölçekleme gücünü keşfetmek.',
                  folderColor: '#ec4899',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'R = log(I/I₀) formülü üzerinde deprem enerjisi oranlarını karşılaştırın.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Logaritmanın gerçek yaşam uygulaması başarıyla incelendi.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-11-bileske-dort-islem',
          code: 'MAT.11.3.3',
          orderNumber: 5,
          themeName: 'Nicelikler ve Değişimler (3) — Fonksiyonlarda Bileşke ve Dört İşlem',
          fullTitle: 'MAT.11.3 (3). Fonksiyonların Bileşkesi ve Dört İşlem',
          lessonHours: 36,
          outcomeCount: 2,
          description: 'İki fonksiyonun bileşkesi (f ∘ g)(x) = f(g(x)), tanım ve değer kümeleri, fonksiyonlarda toplama, çıkarma, çarpma, bölme ve grafik temsilleri.',
          colorTheme: '#f59e0b',
          topics: [
            {
              id: '11-fonk-bileske-islem',
              title: 'Bileşke Fonksiyon ve Fonksiyonel İşlemler',
              code: 'MAT.11.3.7',
              category: 'fonksiyon',
              badge: 'Bileşke Fonksiyon',
              description: '(f ∘ g)(x) ve (g ∘ f)(x) bileşke sıralamasının etkisi, (f ∘ f⁻¹)(x) = x birim fonksiyonu ve çok aşamalı modellemeler.',
              learningOutcomes: [
                'Fonksiyonların bileşkelerine ilişkin muhakeme yapabilme.',
                'Fonksiyonlarda dört işlem özelliklerini uygun cebirsel ve grafik temsillerle yorumlayabilme.',
              ],
              activities: [
                {
                  id: 'act-11-bileske-makinesi',
                  title: 'İki Aşamalı Fonksiyon Makinesi: (f ∘ g)(x)',
                  category: 'fonksiyon',
                  description: 'g(x) = 2x + 1 çıktısının f(u) = u² girdisine dönüştüğü iki aşamalı bileşke sürecini görsel olarak izleyin.',
                  learningGoal: 'Bileşke fonksiyonun iç içe dönüşüm mantığını anlamak.',
                  folderColor: '#f59e0b',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'x değerini girip önce g(x) sonra f(g(x)) çıktısını adım adım takip edin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Bileşke fonksiyon mekanizması kavrandı.',
                },
              ],
            },
          ],
        },
      ],
      topics: [],
    },

    // =========================================================================
    // 12. SINIF (216 Ders Saati — 21 Öğrenme Çıktısı)
    // =========================================================================
    {
      gradeNumber: 12,
      title: '12. Sınıf',
      subtitle: 'Diziler, Polinomlar, Çember ve Katı Cisimler, Değişimin Matematiği (Limit & Türev)',
      description: 'Aritmetik ve geometrik diziler, yüksek dereceli polinom fonksiyonlar, çemberin analitik ve geometrik elemanları, katı cisimler (prizma, silindir, piramit, koni, küre), limit ve süreklilik (0/0 belirsizliği), anlık değişim ve türev kuralları, türevin geometrik yorumu (teğet eğimi) ve ekstremum optimizasyon problemleri.',
      themes: [
        {
          id: 'tymm-12-diziler',
          code: 'MAT.12.1.1',
          orderNumber: 1,
          themeName: 'Nicelikler ve Değişimler (1) — Diziler',
          fullTitle: 'MAT.12.1 (1). Aritmetik ve Geometrik Diziler',
          lessonHours: 14,
          outcomeCount: 2,
          description: 'Aritmetik diziler (an = a1 + (n-1)d, Sn = n/2(a1+an)), geometrik diziler (an = a1·r^(n-1), Sn = a1(1-r^n)/(1-r)), gerçek sayı dizileri ile fonksiyonların karşılaştırılması.',
          colorTheme: '#8b5cf6',
          topics: [
            {
              id: '12-dizi-aritmetik-geometrik',
              title: 'Aritmetik ve Geometrik Dizi Toplamları',
              code: 'MAT.12.1.1',
              category: 'sayi',
              badge: 'Diziler',
              description: 'Sabit fark (d) ve sabit oran (r) ile ilerleyen dizilerin genel terimi ve ilk n terim toplamı (Sn).',
              learningOutcomes: [
                'Aritmetik ve geometrik dizilerin özelliklerine ilişkin muhakeme yapabilme.',
                'Dizileri tanım kümesi pozitif tam sayılar olan fonksiyonlar olarak modelleyebilme.',
              ],
              activities: [
                {
                  id: 'act-12-dizi-toplam',
                  title: 'Gauss Toplamı ve Geometrik Seri Görselleştirmesi',
                  category: 'sayi',
                  description: 'Aritmetik dizide terimleri baştan ve sondan eşleştirerek Sn = n(a1+an)/2 bağıntısını geometrik olarak elde edin.',
                  learningGoal: 'Dizi toplam formüllerinin sezgisel kanıtını kavramak.',
                  folderColor: '#8b5cf6',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Terim sayısını artırarak toplamın büyüme hızını inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Dizi toplam bağıntıları başarıyla doğrulandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-12-polinom-fonk',
          code: 'MAT.12.1.2',
          orderNumber: 2,
          themeName: 'Nicelikler ve Değişimler (2) — Polinom ve Rasyonel Fonksiyonlar',
          fullTitle: 'MAT.12.1 (2). Polinom Fonksiyonlar ve Eşitsizlikler',
          lessonHours: 22,
          outcomeCount: 3,
          description: 'Yüksek dereceli polinom fonksiyonlar p(x)=an·xⁿ+...+a0, derecesi, başkatsayısı, sıfırları, sonsuzdaki davranışı, teklik-çiftlik, rasyonel eşitsizlikler ve işaret tabloları.',
          colorTheme: '#06b6d4',
          topics: [
            {
              id: '12-polinom-nitel-grafik',
              title: 'Polinom Fonksiyonların Nitel Özellikleri ve Kökleri',
              code: 'MAT.12.1.4',
              category: 'fonksiyon',
              badge: 'Polinomlar',
              description: '3. ve 4. dereceden polinom grafiklerinin kıvrımları, x eksenini kestiği noktalar (sıfırları) ve sonsuzdaki asimptotik yönü.',
              learningOutcomes: [
                'Gerçek katsayılı tek değişkenli polinom fonksiyonların nitel özelliklerine dair çıkarım yapabilme.',
                'Polinom ve rasyonel fonksiyonlarla ifade edilen eşitsizlikleri işaret tablosuyla çözebilme.',
              ],
              activities: [
                {
                  id: 'act-12-polinom-kokler',
                  title: 'p(x) = (x - a)(x - b)(x - c) Kök ve Grafik Laboratuvarı',
                  category: 'fonksiyon',
                  description: 'Köklerin yerlerini değiştirerek 3. derece eğrinin yerel tepe/çukur noktalarının ve x ekseni kesimlerinin değişimini gözlemleyin.',
                  learningGoal: 'Polinom kökleri ile grafik kıvrımları arasındaki ilişkiyi anlamak.',
                  folderColor: '#06b6d4',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'a, b, c köklerini kaydırarak grafiğin dalgalanışını izleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Polinom fonksiyon grafiği başarıyla analiz edildi.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-12-cember-daire',
          code: 'MAT.12.2',
          orderNumber: 3,
          themeName: 'Geometrik Şekiller — Çember ve Daire',
          fullTitle: 'MAT.12.2. Çemberin Elemanları, Açıları ve Dairenin Alanı',
          lessonHours: 26,
          outcomeCount: 3,
          description: 'Kesen, kiriş, teğet, çap ve yay elemanları, merkez açı, çevre açı, teğet-kiriş açı, iç ve dış açı özellikleri, kirişler dörtgeni, teğetler dörtgeni, dairenin alanı ve daire dilimi.',
          colorTheme: '#10b981',
          topics: [
            {
              id: '12-geo-cember-acilar',
              title: 'Çemberde Açılar ve Teğet-Kiriş Özellikleri',
              code: 'MAT.12.2.2',
              category: 'geometri',
              badge: 'Çember Geometrisi',
              description: 'Aynı yayı gören çevre açının ölçüsünün merkez açının yarısı olması (θ = 2α), çapı gören çevre açının 90° olması, teğetin yarıçapa dikliği.',
              learningOutcomes: [
                'Çemberde açı, kiriş ve teğet özellikleri ile ilgili çıkarım yapabilme.',
                'Çemberin açı, kiriş, teğet özelliklerini ve dairenin alanını kullanarak problem çözebilme.',
              ],
              activities: [
                {
                  id: 'act-12-merkez-cevre-aci',
                  title: 'Merkez Açı = 2 × Çevre Açı İnteraktif İspatı',
                  category: 'geometri',
                  description: 'Çember üzerindeki çevre açı köşesini yay boyunca hareket ettirerek açının değerinin değişmediğini ve merkez açının daima yarısı olduğunu test edin.',
                  learningGoal: 'Aynı yayı gören çevre açıların eşitliğini ve merkez açı bağıntısını keşfetmek.',
                  folderColor: '#10b981',
                  previewType: 'circle_radius',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Çevre açının köşesini çember üzerinde gezdirin.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Çemberde açı teoremleri başarıyla doğrulandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-12-kati-cisimler',
          code: 'MAT.12.3',
          orderNumber: 4,
          themeName: 'Geometrik Cisimler (Katı Cisimler)',
          fullTitle: 'MAT.12.3. Prizma, Silindir, Piramit, Koni ve Küre',
          lessonHours: 30,
          outcomeCount: 3,
          description: 'Dik prizma ve dik dairesel silindirin elemanları, cisim köşegeni, dik piramit, dik dairesel koni ve kürenin yüzey alanı ve hacim bağıntıları (Vpiramit = 1/3·B·h, Vkoni = 1/3·πr²h, Vküre = 4/3·πr³, Aküre = 4πr²).',
          colorTheme: '#f59e0b',
          topics: [
            {
              id: '12-geo-kati-cisim-hacim',
              title: 'Katı Cisimlerin Açınımları, Alan ve Hacimleri',
              code: 'MAT.12.3.2',
              category: 'geometri',
              badge: 'Katı Cisimler',
              description: 'Silindir ile koni (1/3 oranı), prizma ile piramit ve Arşimet\'in silindir-küre hacim ilişkisi.',
              learningOutcomes: [
                'Dik prizma ile silindirden yararlanarak piramit, koni ve kürenin hacim bağıntılarına analojik akıl yürütebilme.',
                'Katı cisimlerin alan ve hacim bağıntılarını mimari ve mühendislik problemlerinde kullanabilme.',
              ],
              activities: [
                {
                  id: 'act-12-silindir-koni-hacim',
                  title: 'Silindir ve Koni Hacim Oranı (3:1) Deneyi',
                  category: 'geometri',
                  description: 'Taban yarıçapı ve yüksekliği aynı olan koninin hacminin silindirin tam 1/3\'ü olduğunu su doldurma analojisiyle inceleyin.',
                  learningGoal: 'Koni ve piramitlerdeki 1/3 katsayısının geometrik kökenini kavramak.',
                  folderColor: '#f59e0b',
                  previewType: 'prism_volume',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Yarıçap ve yükseklik değerlerini değiştirerek hacimleri karşılaştırın.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Katı cisimler hacim bağıntısı başarıyla incelendi.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-12-degisim-limit',
          code: 'MAT.12.4.1',
          orderNumber: 5,
          themeName: 'Değişimin Matematiği (1) — Limit ve Süreklilik',
          fullTitle: 'MAT.12.4 (1). Fonksiyonlarda Limit ve Süreklilik',
          lessonHours: 28,
          outcomeCount: 4,
          description: 'Bir noktaya sağdan ve soldan yaklaşma, limit tanımı, sonsuzdaki limit ve asimptotlar, 0/0 belirsizliğinin çarpanlara ayırma ile giderilmesi, bir noktada süreklilik şartı (lim f(x) = f(a)).',
          colorTheme: '#ec4899',
          topics: [
            {
              id: '12-kalkulus-limit-tanimi',
              title: 'Yaklaşım Fikri, Limit ve 0/0 Belirsizliği',
              code: 'MAT.12.4.1',
              category: 'fonksiyon',
              badge: 'Limit',
              description: 'Sağdan limit lim(x→a⁺)f(x) ve soldan limit lim(x→a⁻)f(x) eşitliği, tanımsızlık ile belirsizlik farkı ve çarpanlara ayırma ile belirsizlik giderme.',
              learningOutcomes: [
                'Fonksiyonların belirli bir nokta civarındaki veya sonsuzdaki davranışını limit kavramıyla grafikler üzerinden yorumlayabilme.',
                '0/0 belirsizliğini cebirsel sadeleştirme ile ortadan kaldırabilme.',
                'Bir fonksiyonun tanımlı olduğu noktadaki sürekliliğini limit eşitliğiyle değerlendirebilme.',
              ],
              activities: [
                {
                  id: 'act-12-limit-yaklasim',
                  title: 'Sağdan ve Soldan Yaklaşım ile Limit Bulucu',
                  category: 'fonksiyon',
                  description: 'Grafik üzerindeki x noktasını hedeflenen a kritik değerine sağdan ve soldan yaklaştırarak f(x) değerlerinin ortak bir L sayısına yaklaşmasını gözlemleyin.',
                  learningGoal: 'Limitin sezgisel ve grafiksel yaklaşım mantığını kavramak.',
                  folderColor: '#ec4899',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'x değerini kritik noktaya doğru sürükleyip sağ ve sol limit değerlerini karşılaştırın.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Limit yaklaşım mantığı başarıyla kavrandı.',
                },
                {
                  id: 'act-12-belirsizlik-giderme',
                  title: 'f(x) = (x² - 4)/(x - 2) Boşluklu Grafik ve 0/0 Belirsizliği',
                  category: 'fonksiyon',
                  description: 'x = 2 noktasında 0/0 belirsizliği olan fonksiyonda (x-2)(x+2)/(x-2) = x+2 sadeleştirmesiyle limitin 4 olduğunu ve delikli (boşluklu) grafiği inceleyin.',
                  learningGoal: 'Belirsizlik ile süreksizlik arasındaki farkı anlamak.',
                  folderColor: '#06b6d4',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'x=2 civarındaki tablo değerlerini ve limiti inceleyin.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! 0/0 belirsizliğinin grafiksel çözümü başarıyla tamamlandı.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-12-degisim-turev-tanim',
          code: 'MAT.12.4.2',
          orderNumber: 6,
          themeName: 'Değişimin Matematiği (2) — Türev Kavramı ve Kuralları',
          fullTitle: 'MAT.12.4 (2). Anlık Değişim Oranı ve Türev Kuralları',
          lessonHours: 28,
          outcomeCount: 3,
          description: 'Ortalama değişim oranından anlık değişim oranına geçiş (kesen doğrusundan teğet doğrusuna), türevin limit tanımı f\'(x)=lim(h→0)[f(x+h)-f(x)]/h, diferansiyel dy=f\'(x)dx, türev alma kuralları (xⁿ, √x, 1/x, toplam, fark, çarpım, bölüm, bileşke), türevlenemeyen köşe ve kırılma noktaları.',
          colorTheme: '#06b6d4',
          topics: [
            {
              id: '12-kalkulus-anlik-degisim-turev',
              title: 'Anlık Değişim Oranı ve Türevin Limit Tanımı',
              code: 'MAT.12.4.5',
              category: 'fonksiyon',
              badge: 'Türev Tanımı',
              description: 'Kesen doğrusunun eğiminin h→0 limitinde teğet doğrusunun eğimine dönüşmesi ve f\'(x) türev alma kuralları.',
              learningOutcomes: [
                'Bir fonksiyonun belirli bir nokta civarındaki değişim oranından anlık değişim oranı ve türev kavramına ulaşabilme.',
                'Türev kurallarını (toplam, çarpım, bölüm, zincir kuralı) limit tanımıyla ispatlayabilme.',
                'Fonksiyonların köşe ve süreksizlik noktalarında neden türevinin olmadığını açıklayabilme.',
              ],
              activities: [
                {
                  id: 'act-12-kesen-teget-limit',
                  title: 'Kesen Doğrusundan Teğet Doğrusuna (h → 0)',
                  category: 'fonksiyon',
                  description: 'f(x) = x² eğrisi üzerinde B(x+h, f(x+h)) noktasını A(x, f(x)) noktasına yaklaştırarak kesen doğrusunun teğet doğrusuna dönüşümünü izleyin.',
                  learningGoal: 'Türevin teğet eğimi olarak limit tanımını geometrik görmek.',
                  folderColor: '#06b6d4',
                  previewType: 'slope_line',
                  initialObjects: [],
                  mission: {
                    type: 'slope_explorer',
                    currentSliders: [
                      { name: 'h', label: 'Aralık (h)', min: 0.05, max: 2, step: 0.05, value: 1 },
                    ],
                  },
                  steps: [{ stepNumber: 1, instruction: 'h değerini 1.0\'den 0.05\'e doğru küçülterek kesen eğiminin anlık teğet eğimine (2x) yaklaştığını görün.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Türevin geometrik kökeni başarıyla keşfedildi.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-12-degisim-turev-geometri',
          code: 'MAT.12.4.3',
          orderNumber: 7,
          themeName: 'Değişimin Matematiği (3) — Türevin Geometrik Yorumu ve Optimizasyon',
          fullTitle: 'MAT.12.4 (3). Teğet Eğimi, Ekstremum ve Maksimum-Minimum Problemleri',
          lessonHours: 28,
          outcomeCount: 2,
          description: 'Teğet doğrusunun eğimi mt = f\'(x0), artanlık-azalanlık aralıkları (f\' > 0, f\' < 0), yerel ve mutlak ekstremum noktaları (1. türev tablosu), Rolle ve Ortalama Değer Teoremleri, maksimum-minimum (optimizasyon) modellemeleri.',
          colorTheme: '#3b82f6',
          topics: [
            {
              id: '12-kalkulus-teget-ekstremum-optimizasyon',
              title: 'Teğet Eğimi, Ekstremum Noktalar ve Optimizasyon',
              code: 'MAT.12.4.8',
              category: 'fonksiyon',
              badge: 'Optimizasyon',
              description: 'Türevin sıfır olduğu tepe/çukur noktalar f\'(x) = 0, en büyük alan, en küçük maliyet ve en yüksek kâr problemleri.',
              learningOutcomes: [
                'Bir fonksiyonun ve türev fonksiyonunun grafik temsilleri arasındaki ilişkiyi çözümleyebilme.',
                'Gerçek yaşam durumlarında türevi kullanarak maksimum-minimum (optimizasyon) problemlerini çözebilme.',
              ],
              activities: [
                {
                  id: 'act-12-teget-egrisi',
                  title: 'Eğriye Teğet Çizici ve Eğim Göstergesi (m = f\'(x))',
                  category: 'fonksiyon',
                  description: 'f(x) = x³ - 3x eğrisi üzerinde noktayı gezdirdikçe teğetin eğiminin tepede m=0 olduğunu, artan aralıkta pozitif, azalan aralıkta negatif olduğunu izleyin.',
                  learningGoal: 'Türevin işareti ile artanlık/azalanlık ilişkisini kavramak.',
                  folderColor: '#3b82f6',
                  previewType: 'slope_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Teğet noktasını sürükleyerek yerel maksimum (x=-1) ve yerel minimum (x=1) noktalarındaki m=0 durumunu doğrulayın.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Teğet eğimi ve ekstremum noktaları başarıyla çözümlendi.',
                },
                {
                  id: 'act-12-max-kutu-hacim',
                  title: 'Maksimum Hacimli Açık Kutu Optimizasyonu',
                  category: 'fonksiyon',
                  description: 'Karton köşelerinden kesilen x kareleri ile oluşan kutunun hacmini V(x) = x(20-2x)² olarak modelleyin ve türevle V\'(x)=0 noktasında en büyük hacmi bulun.',
                  learningGoal: 'Gerçek yaşam problemlerinde türevle optimizasyon yapmayı keşfetmek.',
                  folderColor: '#10b981',
                  previewType: 'prism_volume',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'x kesim miktarını ayarlayarak kutu hacminin ulaştığı tepe değerini bulun.' }],
                  validationRules: [],
                  completedMessage: 'Harika! Maksimum-minimum optimizasyon problemi başarıyla çözüldü.',
                },
              ],
            },
          ],
        },
        {
          id: 'tymm-12-hazir-veriler',
          code: 'MAT.12.5',
          orderNumber: 8,
          themeName: 'Hazır Veriler Üzerinde Çalışma',
          fullTitle: 'MAT.12.5. Hazır Veriler Üzerinde İstatistiksel Çalışma',
          lessonHours: 30,
          outcomeCount: 1,
          description: 'Toplumsal ve bilimsel gerçek veri setleri (küresel iklim değişikliği, nüfus artışı, sağlık verileri) üzerinden istatistiksel araştırma tasarımları, çok değişkenli analizler ve veriye dayalı karar verme.',
          colorTheme: '#6366f1',
          topics: [
            {
              id: '12-ist-hazir-veri-analiz',
              title: 'Hazır Veriye Dayalı İstatistiksel Araştırma',
              code: 'MAT.12.5.1',
              category: 'veri',
              badge: 'Büyük Veri & Karar',
              description: 'Resmî kurumlardan elde edilen gerçek verilerle çok değişkenli dağılımların analizi ve raporlaştırılması.',
              learningOutcomes: [
                'Toplumsal ve bilimsel durumlara ilişkin hazır veri ile çalışabilme ve hazır veriye dayalı karar verebilme.',
                'İstatistiksel sonuçları eleştirel gözle değerlendirip bilimsel rapor sunabilme.',
              ],
              activities: [
                {
                  id: 'act-12-iklim-veri-analiz',
                  title: 'Küresel Sıcaklık ve CO₂ Veri Seti Korelasyonu',
                  category: 'veri',
                  description: 'Son 50 yılın atmosferik CO₂ konsantrasyonu ile ortalama sıcaklık sapması verilerini saçılım grafiğinde karşılaştırıp çıkarımda bulunun.',
                  learningGoal: 'Gerçek veriler üzerinden çok değişkenli istatistiksel muhakeme yürütmek.',
                  folderColor: '#6366f1',
                  previewType: 'number_line',
                  initialObjects: [],
                  steps: [{ stepNumber: 1, instruction: 'Veri dağılımını inceleyerek trend doğrusunu yorumlayın.' }],
                  validationRules: [],
                  completedMessage: 'Tebrikler! Hazır veri araştırması başarıyla tamamlandı.',
                },
              ],
            },
          ],
        },
      ],
      topics: [],
    },
  ],
};
